In [0]:
import numpy as np

In [2]:
from google.colab import drive
drive.mount('/content/drive/')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive/


In [3]:
ls

drive/  sample_data/


In [4]:
cd 'drive/My Drive'

/content/drive/My Drive


In [5]:
cd '2516Project/data'

/content/drive/My Drive/2516Project/data


In [6]:
ls

 articles-training-byarticle-20181122.xml
 articles-training-byarticle-20181122.zip
 articles-training-bypublisher-20181122.xml
 articles-training-bypublisher-20181122.zip
 byarticle_training.csv
'Copy of train.text.tsv'
 fake.csv
 ground-truth-training-byarticle-20181122.xml
 ground-truth-training-byarticle-20181122.zip
 ground-truth-training-bypublisher-20181122.xml
 ground-truth-training-bypublisher-20181122.zip
 news_dataset.csv
 train.elmo.tsv
 train.text.tsv


In [0]:
import pandas as pd
df = pd.read_csv("byarticle_training.csv")

In [8]:
df.head(5)

Unnamed: 0  ...                                 url
0           0  ...           https://www.opednews.com/
1           1  ...        http://bipartisanreport.com/
2           2  ...      https://www.reviewjournal.com/
3           3  ...    https://www.redcuprebellion.com/
4           4  ...  https://www.realclearpolitics.com/

[5 rows x 8 columns]

In [9]:
df

Unnamed: 0  ...                                 url
0             0  ...           https://www.opednews.com/
1             1  ...        http://bipartisanreport.com/
2             2  ...      https://www.reviewjournal.com/
3             3  ...    https://www.redcuprebellion.com/
4             4  ...  https://www.realclearpolitics.com/
..          ...  ...                                 ...
640         640  ...          http://urbanmilwaukee.com/
641         641  ...         http://www.therepublic.com/
642         642  ...           http://www.theweek.co.uk/
643         643  ...              http://truepundit.com/
644         644  ...                https://pjmedia.com/

[645 rows x 8 columns]

In [10]:
for col in df.columns: 
    print(col) 

Unnamed: 0
content
id
published-at
title
bias
hyperpartisan
url


In [0]:
df = df[['content', 'hyperpartisan']]

In [12]:
df

content  hyperpartisan
0    flickrcom Money MID161793 Money Image 401K 201...              1
1    Donald Trump ran many braggadocios largely unr...              1
2    Photo Justin SullivanGetty Images response Joy...              1
3    Colin Kaepernick rightly chose kneel national ...              1
4    Almost halfcentury ago 1968 United States seem...              0
..                                                 ...            ...
640  Donald Trump Photo whitehousegov MADISON – US ...              1
641  President Donald Trump Tuesday began dismantli...              0
642  US Supreme Court ruled Donald Trump’s ban trav...              0
643  ExFBI Director James Comey went rogue accordin...              0
644  Ashley Judd absolute worst want like really So...              1

[645 rows x 2 columns]

In [13]:
df['hyperpartisan'].value_counts()

0    407
1    238
Name: hyperpartisan, dtype: int64

In [14]:
!pip install transformers

     |████████████████████████████████| 573kB 2.7MB/s 
     |████████████████████████████████| 1.0MB 50.4MB/s 
     |████████████████████████████████| 3.7MB 51.8MB/s 
     |████████████████████████████████| 890kB 47.7MB/s 
  Created wheel for sacremoses: filename=sacremoses-0.0.41-cp36-none-any.whl size=893334 sha256=358177942b90bd21df3dc1bb561e01cafd0bc20dd6bef70b5f4dc8ff61b08643
  Stored in directory: /root/.cache/pip/wheels/22/5a/d4/b020a81249de7dc63758a34222feaa668dbe8ebfe9170cc9b1
Successfully built sacremoses


In [15]:
import torch
from transformers import BertTokenizer, BertModel, BertForMaskedLM

model_class, tokenizer_class, pretrained_weights = (BertModel, BertTokenizer, 'bert-base-uncased')

tokenizer = tokenizer_class.from_pretrained(pretrained_weights)
model = model_class.from_pretrained(pretrained_weights)

In [0]:
# !pip install pytorch-pretrained-bert==0.4.0 
# import torch
# from pytorch_pretrained_bert import BertTokenizer, BertModel, BertForMaskedLM
# tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
# model = BertModel.from_pretrained('bert-base-uncased')
# tokenized = df['content'].apply(lambda x: tokenizer.tokenize(x))
# print(tokenized)

In [0]:
tokenized = df['content'].apply((lambda x: tokenizer.encode(x, add_special_tokens=True, max_length=512)))

In [0]:
# masked_index = 6
# # tokenized_text[masked_index] = '[MASK]'
# masked_tokens = tokenized.apply(lambda x : df[masked_index].replace([masked_index], 'MASK'))

In [19]:
print(tokenized)

0      [101, 17312, 29566, 2213, 2769, 3054, 16048, 1...
1      [101, 6221, 8398, 2743, 2116, 23678, 9365, 979...
2      [101, 6302, 6796, 7624, 18150, 3723, 4871, 343...
3      [101, 6972, 10556, 13699, 11795, 6799, 2157, 2...
4      [101, 2471, 2431, 13013, 13098, 3283, 3380, 21...
                             ...                        
640    [101, 6221, 8398, 6302, 2317, 4580, 3995, 2615...
641    [101, 2343, 6221, 8398, 9857, 2211, 4487, 1151...
642    [101, 2149, 4259, 2457, 5451, 6221, 8398, 1521...
643    [101, 4654, 26337, 2072, 2472, 2508, 2272, 210...
644    [101, 9321, 20128, 7619, 5409, 2215, 2066, 242...
Name: content, Length: 645, dtype: object


In [0]:
# print(masked_tokens)

In [0]:
# print(masked_tokens)

In [0]:
# indexed_tokens = tokenized.apply(lambda x: tokenizer.convert_tokens_to_ids(x))

In [0]:
# print(indexed_tokens)

In [0]:
max_len = 0
for i in tokenized.values:
    if len(i) > max_len:
        max_len = len(i)

padded = np.array([i + [0]*(max_len-len(i)) for i in tokenized.values])

In [25]:
np.array(padded).shape

(645, 512)

In [26]:
attention_mask = np.where(padded != 0, 1, 0)
attention_mask.shape

print(attention_mask)

[[1 1 1 ... 1 1 1]
 [1 1 1 ... 0 0 0]
 [1 1 1 ... 0 0 0]
 ...
 [1 1 1 ... 0 0 0]
 [1 1 1 ... 0 0 0]
 [1 1 1 ... 0 0 0]]


In [27]:
print(attention_mask.shape)

(645, 512)


In [0]:
input_ids = torch.tensor(padded)  
attention_mask = torch.tensor(attention_mask)

with torch.no_grad():
    last_hidden_states = model(input_ids, attention_mask=attention_mask)

In [0]:
features = last_hidden_states[0][:,0,:].numpy()

In [0]:
import numpy as np
import pandas as pd
import torch
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split

In [31]:
labels = df['hyperpartisan']
train_features, test_features, train_labels, test_labels = train_test_split(features, labels)
print(train_features)

[[ 0.08407423 -0.04466816  0.37508845 ... -0.3208932  -0.07469715
   0.13360111]
 [-0.10133707  0.03036474  0.2826926  ... -0.15896918  0.18710497
  -0.08542342]
 [ 0.17798375 -0.00699253  0.14550076 ... -0.2760419   0.30350393
   0.00577985]
 ...
 [-0.10005743  0.05917588 -0.1064268  ... -0.19182913  0.5868409
   0.2696891 ]
 [-0.2493248   0.1706006   0.16158238 ... -0.06843587  0.23748477
   0.07174361]
 [ 0.11964615  0.03256379  0.47050133 ... -0.3832115   0.27464053
   0.1900863 ]]


In [32]:
clf = LogisticRegression()
clf.fit(train_features, train_labels)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [33]:
clf.score(test_features, test_labels)

0.8148148148148148

In [0]:
# print(tokenized.values)

In [0]:
# print(padded)

In [36]:
text = 'blah blah blah I am a king. Who are you? Typing some random shit! I killed myself 2435123'
token = tokenizer.encode(text, add_special_tokens=True)
in_id = tokenizer.convert_tokens_to_ids(token)
in_id = torch.tensor(in_id).unsqueeze(0)
with torch.no_grad():
    last_hidden_state = model(in_id)
feature = last_hidden_state[0][:,0,:].numpy()

clf.predict(feature)

array([0])